### ISSUE TITLE
Need InputFormatFactory

### ISSUE THREAD

**Issue by zzxx-husky** [husky-team/husky#107]
Similar to obj list and channels, design a factory to store all the input formats so that input formats will not be released when they're out of their scope.

**Comment by ddmbr** [comment]
I'll think of the Factory pattern when I see such name. Maybe we should use a more accurate name later? This all applies for many existing classes that are named in this way.

**Comment by kygx-legend** [comment]
`InputForamtGenerator`?

**Comment by ddmbr** [comment]
OK let me be specific. Factory is OK. But then a Factory normally should not store things by itself. So we may do some object pools probably, along with factories.

**Comment by xwkuang5** [comment]
Should I use a `inputformat_factory` to decorate `inputformat_factory_base` just like `channel_factory`?

**Comment by Yuzhen11** [comment]
Maybe you don't need to. channel_factory_base is used to do unit test and doesn't depend on Context. However, I think all input format need to depend on Context.

**Comment by xwkuang5** [comment]
I want to add `drop_all_objlists`, `drop_all_inputformats` and `drop_all_channels` to the `RegSessionFinalizer` so that when `thread_finalize` is called, all the channels, objlist and inputformat will be properly freed. As suggested by @zzxx-husky , there needs to be priority control over which objects need to be freed first. I want to add a priority parameter to the `finalizer` method, doing something like this:
`static thread_local base::RegSessionThreadFinalizer finalize_all_channels(priority, []() { ChannelFactoryBase::drop_all_channels(); }); `
Then we can do a sorting of priority inside `thread_finalize` and free the channels first, which has the highest priority, followed by objlist and inputformat. What do you think? @ddmbr @Yuzhen11 @kygx-legend

**Comment by Yuzhen11** [comment]
I think yes, priority is needed in this case.
