### ISSUE TITLE
A method to balance the objects in different threads of the same list

### ISSUE THREAD

**Issue by Yuzhen11** [husky-team/husky#130]
We may need a method to balance the objects in different threads of the same list. Considering sometimes we want the objects to be balanced but globalize method is too heavy, a light weight method may be necessary.

Liu zhi will take this issue, and a prototype is almost done.

**Comment by lmatz** [comment]
Did a comparison between the prototype of the light-weight balance method and the globalize method.
<img width="929" alt="balance_vs_globalize" src="https://cloud.githubusercontent.com/assets/5791930/20423272/5ff6c422-adaa-11e6-89f3-543609c7b2b1.png">
  This is a simple implementation which does not take care of any environment issues such as locality and network bandwidth. It can be seen that there is overhead for the algorithm itself to run since all threads need to receive the information about the number of objects in other threads, which is a N-to-N network communications. But when the system has billions of objects needed to be balanced, the light-weight version is almost twice as fast as the globalize method. 
  An optimization I think might work is to let all threads in one process try to be as equal as possible before it decides how the transfer between different nodes should work, since the time of balancing will depend on the longest time one thread spent on this function.
  Another one is that if every worker can know the data transfer rate between itself and different nodes dynamically. It might be worthy formulating this into an integer linear programming problem and introducing some third party library to solve it. But I am not sure whether Husky is going support to this.

**Comment by ddmbr** [comment]
`globalize` tends to move all the data around, so there should be a method which moves the minimal of data. I think the optimal strategy may be that we use an Aggregator to let every thread learn the distribution of the data, and then only move data out when a thread is holding more than average? I guess you are doing something like this?

**Comment by lmatz** [comment]
Yes, my current implementation uses broadcast channel to let every thread know the distribution of the data and it moves the minimal of data as you described.

**Comment by Yuzhen11** [comment]
Looks good. You may try to polish your implementation and make a pull request.

**Comment by lmatz** [comment]
Should I separate the balance method and the algorithm it uses in two different files? Which directory should the algorithm live in? lib?

**Comment by ddmbr** [comment]
Since core components do not depend on it, your method should live in `lib/`. It's a good idea to separate the concept and the actual implementation so that you can choose between different strategies (if there are).
