### ISSUE TITLE
How to initialise an aggregator for vectors of DenseVector?

### ISSUE THREAD

**Issue by rylanchiu** [husky-team/husky#196]
I'd like to initialise an aggregator `Aggregator<vector<DenseVector<double>>>` in the following way:

     int num_top = 20;
     int N = 5000;
     Aggregator<vector<DenseVector<double>>> Theta(vector<DenseVector<double>>(num_top, DenseVector<double>(N, 0)));

But I got such an error:

      required from here
     /home/1155081754/baye_husky/lib/aggregator_object.hpp:40:22: error: no match for 'operator+' (operand types are 'std::vector<husky::lib::Vector<double, false> >' and 'const std::vector<husky::lib::Vector<double, false> >')
     copy_assign(a, a + b);

I am totally lost for this error. Could you please give me some instruction so that I can fix it? Thanks in advance.

**Comment by ddmbr** [comment]
Looks like your are quite new to C++. Please start from here: http://en.cppreference.com/w/cpp/language/operators

**Comment by zzxx-husky** [comment]
Hi @rylanchiu , just a few more words. When you create the aggregator
```c++
Aggregator<vector<DenseVector<double>>> Theta(vector<DenseVector<double>>(num_top, DenseVector<double>(N, 0)));
```
you didn't tell the rule how two `vector<DenseVector<double>>` can be aggregated. The rule should be provided using a lambda as the second argument when creating the aggregator. If the rule is not given, Aggregator will look for `operator+`. Because `vector<DenseVector<double>>` doesn't support `operator+` by default, you get a compilation error.
