### ISSUE TITLE
husky/lib/ml/data_loader.hpp does not set key for the objects?

### ISSUE THREAD

**Issue by ylchan87** [husky-team/husky#204]
https://github.com/husky-team/husky/blob/master/lib/ml/data_loader.hpp#L67

It seems that the data fields were set but not the obj key.
I am having trouble with using globalize on object_list returned from data_loader and I am wondering if this is the cause.

**Comment by TatianaJin** [comment]
1. if you are globalizing `ObjectList` containing LabeledPointHObj, the problem is that the serialization operators << and >> into `BinStream`are not implemented. I will fix it. Thanks for raising the issue.

You can try putting the following codes in the `LabeledPointHObj` class:
`friend BinStream& operator<<(husky::BinStream& stream, LabeledPointHObj<FeatureT, LabelT, is_sparse>& obj) {
    stream << obj.key << obj.x << obj.y;
    return stream;
}

friend BinStream& operator>>(husky::BinStream& stream, LabeledPointHObj<FeatureT, LabelT, is_sparse>& obj) {
    stream >> obj.key >> obj.x >> obj.y;
    return stream;
}`
Then the program should compile. However, without setting the key in data_loader.hpp, the default key will be 0, which means after globalizing the `ObjList` will have all its objects on only one worker according to the hashed value.

2. The `LabeledPointHObj` was not intended to be globalized but just to remain local. The rationale is that 1) there does not seem to be needs for them to communicate, and 2) considering load balancing, if the whole dataset is large, the input format will do the work (e.g. hdfs divide the input file into blocks and each worker will load some of the blocks); and if the dataset is small, there is no need to globalize the list. But there is no settlement yet. If you do find it necessary to globalize the `ObjectList` of LabeledPointHObj, we can figure out a way to assign keys and enable globalization.

**Comment by ylchan87** [comment]
Many thanks for the explanation. I understand your coding choice now.

I was using a small dataset but I globalize the objList to force it be distributed to test my code. Thus my use case is not very realistic.

The only case where this issue might come up is when the data is light, so one node will read it all, while the computation is heavy, so distributing the data to all nodes is preferred. But I guess this scenario should be very rare

**Comment by Toofarto** [comment]
But I think it is common to test our programs with some small datasets for the sake of efficiency. Are there some ways to distribute a small dataset without globalization while using LabeledPointHObj? Currently, my temporary solution is to modify the code in my local branch to make globalization possible but the code is hard to push on GitHub and for the others to reuse.

Moreover, globalization can balance the number of samples on each worker, which can improve the accuracy of the trained model and prevent workers from idling.

Also, I would like to know why LabeledPointHObj was intended to remain local? Becuase it would reduce the functionality of this datatype.
