### ISSUE TITLE
Unexpected blocking in running BroadcastChannel unittest

### ISSUE THREAD

**Issue by kygx-legend** [husky-team/husky#60]
It happens sometimes in travis ci.

`$ ./HuskyUnitTest --gtest_filter=TestBroadcastChannel.Broadcast`
`$ ./HuskyUnitTest --gtest_filter=TestBroadcastChannel.BroadcastClearDict`

**Comment by zzxx-husky** [comment]
This could be caused by Generation count. GenerationBase maintains a map for each thread to record self-generation to each GenerationBase object. The map will be kept in memory and reused until the thread ends. If one GenerationBase object is destroyed and a second GenerationBase object is created and these two object shares the same address, this thread will use previous self-generation remained in the map.

**Comment by Yuzhen11** [comment]
@zzxx-husky If one GenerationBase object is destroyed, we also remove the element in the key. Will this problem still exist?

**Comment by zzxx-husky** [comment]
@Yuzhen11  Unfortunately nope. To ease the use of GenerationBase, self-generation is managed by GenerationBase instead of the users and that's why a map is needed for each thread. But one GenerationBase is shared by threads. And when destroying a GenerationBase object, it's not possible to notify the threads that use it. So the self-generation remains in the map.  But rather than thinking about how to remove the element from the maps, I think it's easier to use a timestamp to check whether a self-generation needs to be initialized.
